import {
  Tenant,
  Deal,
  Document,
  FieldObservation,
  CanonicalField,
  RequirementVersion,
  Task,
  LenderPolicyVersion,
  ConsentRecord,
  LenderCondition,
  DealParticipant,
} from '../types';

export const mockTenant: Tenant = {
  id: 'tenant_apex_cre',
  name: 'Apex Commercial Lending',
  retentionDays: 2555, // 7 years
  createdAt: '2025-01-15T08:00:00Z',
};

export const mockParticipants: DealParticipant[] = [
  {
    id: 'part_1',
    dealId: 'deal_metro_plaza',
    personId: 'user_broker_sarah',
    personName: 'Sarah Jenkins (Senior Broker)',
    role: 'broker',
    permittedScope: { fullAccess: true },
    effectiveFrom: '2026-08-01T00:00:00Z',
  },
  {
    id: 'part_2',
    dealId: 'deal_metro_plaza',
    personId: 'user_borrower_marcus',
    personName: 'Marcus Vance (Borrower Guarantor)',
    role: 'borrower',
    permittedScope: { entityScope: 'Metro Apex Holdings LLC' },
    effectiveFrom: '2026-08-01T00:00:00Z',
  },
  {
    id: 'part_3',
    dealId: 'deal_metro_plaza',
    personId: 'user_processor_david',
    personName: 'David Chen (Loan Processor)',
    role: 'processor',
    permittedScope: { delegatedBy: 'user_broker_sarah' },
    effectiveFrom: '2026-08-05T00:00:00Z',
  },
];

export const mockDeals: Deal[] = [
  {
    id: 'deal_metro_plaza',
    tenantId: 'tenant_apex_cre',
    title: 'Metro Shopping Plaza Acquisition',
    borrowerName: 'Marcus Vance (Metro Apex Holdings LLC)',
    propertyAddress: '450 Metro Boulevard, Austin, TX 78701',
    purpose: 'purchase',
    candidatePrograms: ['conventional', 'sba_504'],
    selectedProgram: 'conventional',
    stage: 'in_review',
    complianceStatus: 'consent_verified',
    ownerUserId: 'user_broker_sarah',
    requestedAmount: { amount: 4500000, currency: 'USD' },
    proposedRate: 0.0675, // 6.75%
    proposedTermMonths: 300, // 25 Years
    createdAt: '2026-09-01T10:30:00Z',
  },
  {
    id: 'deal_logistics_park',
    tenantId: 'tenant_apex_cre',
    title: 'Industrial Logistics Park Refinance',
    borrowerName: 'Elena Rostova (Logistics One LLC)',
    propertyAddress: '1200 Industrial Parkway, Dallas, TX 75201',
    purpose: 'refinance',
    candidatePrograms: ['conventional'],
    selectedProgram: 'conventional',
    stage: 'intake_active',
    complianceStatus: 'pending_consent',
    ownerUserId: 'user_broker_sarah',
    requestedAmount: { amount: 8200000, currency: 'USD' },
    proposedRate: 0.065,
    proposedTermMonths: 240,
    createdAt: '2026-09-12T14:15:00Z',
  },
  {
    id: 'deal_downtown_mixed',
    tenantId: 'tenant_apex_cre',
    title: 'Downtown Mixed-Use Construction',
    borrowerName: 'Robert Vance (Vance Development Inc)',
    propertyAddress: '88 5th Avenue, Houston, TX 77002',
    purpose: 'construction',
    candidatePrograms: ['sba_504'],
    selectedProgram: 'sba_504',
    stage: 'provisional',
    complianceStatus: 'pending_consent',
    ownerUserId: 'user_broker_sarah',
    requestedAmount: { amount: 12000000, currency: 'USD' },
    proposedRate: 0.0725,
    proposedTermMonths: 180,
    createdAt: '2026-09-20T11:00:00Z',
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc_tax_2024',
    dealId: 'deal_metro_plaza',
    storageKey: 's3://apex-docs/deals/metro_plaza/2024_tax_1120s.pdf',
    filename: '2024_Form_1120S_Metro_Apex_Holdings.pdf',
    sha256Digest: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    uploaderId: 'user_borrower_marcus',
    uploaderRole: 'borrower',
    sourceEventId: 'evt_intake_whatsapp_091',
    entityId: 'ent_metro_apex_llc',
    period: '2024-FY',
    pageCount: 14,
    processingState: 'extracted',
    acceptanceState: 'intake_only',
    docType: 'tax_return',
    uploadedAt: '2026-09-02T11:20:00Z',
    ocrTextPreview: `FORM 1120-S U.S. Income Tax Return for an S Corporation (2024)
Name: Metro Apex Holdings LLC  EIN: 84-2910394
Line 1a Gross receipts or sales: $1,850,000
Line 6 Total Income: $1,240,000
Line 21 Ordinary business income (loss): $585,000
Page 4 Schedule K - Shareholders' Shares of Income...`,
  },
  {
    id: 'doc_pnl_2024',
    dealId: 'deal_metro_plaza',
    storageKey: 's3://apex-docs/deals/metro_plaza/2024_P_and_L_Statement.pdf',
    filename: '2024_YTD_Profit_Loss_Statement.pdf',
    sha256Digest: 'a45f91e320491823901bca293849129038290e290f1293019230912301923011',
    uploaderId: 'user_borrower_marcus',
    uploaderRole: 'borrower',
    sourceEventId: 'evt_upload_web_104',
    entityId: 'ent_metro_apex_llc',
    period: '2024-FY',
    pageCount: 3,
    processingState: 'extracted',
    acceptanceState: 'intake_only',
    docType: 'operating_statement',
    uploadedAt: '2026-09-03T09:14:00Z',
    ocrTextPreview: `Metro Shopping Plaza - Annual Profit & Loss Statement (Jan-Dec 2024)
Rental Income: $1,120,000
CAM Reimbursements: $180,000
Gross Operating Revenues: $1,300,000
Operating Expenses (Insurance, Taxes, Maintenance): $715,000
Net Operating Income (NOI): $585,000`,
  },
  {
    id: 'doc_appraisal_2026',
    dealId: 'deal_metro_plaza',
    storageKey: 's3://apex-docs/deals/metro_plaza/Appraisal_Report_450_Metro.pdf',
    filename: 'Commercial_Appraisal_Report_August2026.pdf',
    sha256Digest: '8c80123981029381029380129381209381092381290381029381029381029381',
    uploaderId: 'user_broker_sarah',
    uploaderRole: 'broker',
    sourceEventId: 'evt_cpa_upload_009',
    entityId: 'ent_metro_apex_llc',
    period: '2026-Q3',
    pageCount: 45,
    processingState: 'reviewed',
    acceptanceState: 'lender_accepted',
    docType: 'appraisal',
    uploadedAt: '2026-09-10T16:45:00Z',
    ocrTextPreview: `INDEPENDENT COMMERCIAL REAL ESTATE APPRAISAL REPORT
Subject Property: 450 Metro Blvd, Austin, TX
Appraised Fair Market Value (As-Is): $6,200,000
Cap Rate Applied: 6.85%
Building Size: 28,400 sq.ft.`,
  },
];

export const mockObservations: FieldObservation[] = [
  {
    id: 'obs_noi_01',
    dealId: 'deal_metro_plaza',
    fieldKey: 'noi.annual',
    value: { amount: 585000, currency: 'USD' },
    unit: 'USD/year',
    entityId: 'ent_metro_apex_llc',
    period: '2024-FY',
    sourceDocId: 'doc_tax_2024',
    sourceDocName: '2024_Form_1120S_Metro_Apex_Holdings.pdf',
    sourcePage: 1,
    sourceRegion: { x: 120, y: 340, width: 240, height: 40 },
    extractionMethod: 'llm',
    confidence: 0.96,
    reviewStatus: 'candidate',
  },
  {
    id: 'obs_debt_01',
    dealId: 'deal_metro_plaza',
    fieldKey: 'debt.existing_monthly',
    value: { amount: 12400, currency: 'USD' },
    unit: 'USD/month',
    entityId: 'ent_metro_apex_llc',
    period: '2024-FY',
    sourceDocId: 'doc_pnl_2024',
    sourceDocName: '2024_YTD_Profit_Loss_Statement.pdf',
    sourcePage: 2,
    sourceRegion: { x: 80, y: 220, width: 200, height: 35 },
    extractionMethod: 'llm',
    confidence: 0.92,
    reviewStatus: 'confirmed',
  },
  {
    id: 'obs_appraisal_01',
    dealId: 'deal_metro_plaza',
    fieldKey: 'property.appraised_value',
    value: { amount: 6200000, currency: 'USD' },
    unit: 'USD',
    entityId: 'ent_metro_apex_llc',
    period: '2026-Q3',
    sourceDocId: 'doc_appraisal_2026',
    sourceDocName: 'Commercial_Appraisal_Report_August2026.pdf',
    sourcePage: 1,
    sourceRegion: { x: 150, y: 180, width: 280, height: 45 },
    extractionMethod: 'ocr',
    confidence: 0.99,
    reviewStatus: 'confirmed',
  },
  {
    id: 'obs_borrower_name',
    dealId: 'deal_metro_plaza',
    fieldKey: 'borrower.entity_name',
    value: 'Metro Apex Holdings LLC',
    sourceDocId: 'doc_tax_2024',
    sourceDocName: '2024_Form_1120S_Metro_Apex_Holdings.pdf',
    sourcePage: 1,
    sourceRegion: { x: 100, y: 100, width: 300, height: 30 },
    extractionMethod: 'llm',
    confidence: 0.98,
    reviewStatus: 'confirmed',
  },
];

export const mockCanonicalFields: CanonicalField[] = [
  {
    id: 'cf_debt_monthly',
    dealId: 'deal_metro_plaza',
    fieldKey: 'debt.existing_monthly',
    fieldLabel: 'Existing Monthly Debt Service',
    acceptedValue: { amount: 12400, currency: 'USD' },
    sourceObservationId: 'obs_debt_01',
    reviewerId: 'user_broker_sarah',
    reviewerName: 'Sarah Jenkins',
    reviewedAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'cf_appraised_val',
    dealId: 'deal_metro_plaza',
    fieldKey: 'property.appraised_value',
    fieldLabel: 'Appraised Property Value',
    acceptedValue: { amount: 6200000, currency: 'USD' },
    sourceObservationId: 'obs_appraisal_01',
    reviewerId: 'user_broker_sarah',
    reviewerName: 'Sarah Jenkins',
    reviewedAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'cf_entity_name',
    dealId: 'deal_metro_plaza',
    fieldKey: 'borrower.entity_name',
    fieldLabel: 'Borrower Entity Name',
    acceptedValue: 'Metro Apex Holdings LLC',
    sourceObservationId: 'obs_borrower_name',
    reviewerId: 'user_broker_sarah',
    reviewerName: 'Sarah Jenkins',
    reviewedAt: '2026-09-16T11:05:00Z',
  },
];

export const mockRequirementCatalog: RequirementVersion[] = [
  {
    id: 'req_v_tax_2yr',
    requirementId: 'req_tax_returns',
    title: 'Business Tax Returns (2 Consecutive Years)',
    description: 'Signed federal tax returns (Form 1120-S or 1065) including all K-1 schedules for the last 2 fiscal years.',
    program: 'conventional',
    purpose: 'purchase',
    applicabilityExpr: { entityStructure: ['S-Corp', 'LLC', 'Partnership'] },
    evidenceSpec: {
      requiredDocType: 'tax_return',
      periodRequired: '2 years',
      acceptedFormats: ['pdf'],
    },
    sourcePolicy: 'Apex Credit Manual Sec 4.1',
    effectiveFrom: '2025-01-01T00:00:00Z',
    criticalFlag: true,
  },
  {
    id: 'req_v_appraisal',
    requirementId: 'req_property_appraisal',
    title: 'Independent Certified Appraisal Report',
    description: 'Full MAI certified appraisal report dated within 180 days showing fair market value and capitalization rate.',
    program: 'conventional',
    purpose: 'purchase',
    applicabilityExpr: { loanAmountMin: 1000000 },
    evidenceSpec: {
      requiredDocType: 'appraisal',
      acceptedFormats: ['pdf'],
    },
    sourcePolicy: 'FIRREA Regulatory Compliance Policy',
    effectiveFrom: '2025-01-01T00:00:00Z',
    criticalFlag: true,
  },
  {
    id: 'req_v_noi_statement',
    requirementId: 'req_operating_pnl',
    title: 'Year-to-Date Operating Profit & Loss Statement',
    description: 'Detailed operating P&L statement demonstrating Net Operating Income (NOI) signed by CPA or Borrower.',
    purpose: 'purchase',
    applicabilityExpr: {},
    evidenceSpec: {
      requiredDocType: 'operating_statement',
      acceptedFormats: ['pdf', 'xlsx'],
    },
    sourcePolicy: 'Underwriting Standard UW-202',
    effectiveFrom: '2025-01-01T00:00:00Z',
    criticalFlag: true,
  },
  {
    id: 'req_v_borrower_consent',
    requirementId: 'req_consent_signature',
    title: 'Lender Submission & Verification Consent',
    description: 'Executed Borrower Authorization and Consent to release financial data to participating credit institutions.',
    applicabilityExpr: {},
    evidenceSpec: {
      requiredDocType: 'consent_record',
      acceptedFormats: ['digital_signature', 'pdf'],
    },
    sourcePolicy: 'Gramm-Leach-Bliley Privacy Rule',
    effectiveFrom: '2025-01-01T00:00:00Z',
    criticalFlag: true,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task_01',
    dealId: 'deal_metro_plaza',
    requirementId: 'req_tax_returns',
    title: 'Provide 2023 & 2024 Business Tax Returns (1120-S)',
    description: 'Upload full signed returns with all Schedule K-1 forms.',
    assigneeRole: 'borrower',
    status: 'completed',
    dueDate: '2026-09-10T00:00:00Z',
    evidenceRefs: ['doc_tax_2024'],
  },
  {
    id: 'task_02',
    dealId: 'deal_metro_plaza',
    requirementId: 'req_operating_pnl',
    title: 'Confirm & Reconcile Annual Net Operating Income (NOI)',
    description: 'Review extracted NOI field candidate of $585,000 from 2024 P&L statement against tax return.',
    assigneeRole: 'broker',
    status: 'in_progress',
    dueDate: '2026-09-28T00:00:00Z',
    evidenceRefs: ['doc_pnl_2024', 'doc_tax_2024'],
  },
  {
    id: 'task_03',
    dealId: 'deal_metro_plaza',
    requirementId: 'req_property_appraisal',
    title: 'Review Appraisal Report & Appraised Value',
    description: 'Verify MAI appraisal report of $6,200,000 and confirm canonical property value field.',
    assigneeRole: 'processor',
    status: 'completed',
    dueDate: '2026-09-20T00:00:00Z',
    evidenceRefs: ['doc_appraisal_2026'],
  },
  {
    id: 'task_04',
    dealId: 'deal_metro_plaza',
    requirementId: 'req_consent_signature',
    title: 'Borrower Consent for Lender Submission',
    description: 'Verify active consent record for transmitting package snapshot to lender.',
    assigneeRole: 'broker',
    status: 'completed',
    dueDate: '2026-09-15T00:00:00Z',
    evidenceRefs: [],
  },
];

export const mockLenderPolicy: LenderPolicyVersion = {
  id: 'lp_2026_apex_prime',
  lenderId: 'lender_apex_bank',
  lenderName: 'Apex Commercial Bank',
  product: 'Commercial Real Estate Senior Debt',
  criteria: {
    minDscr: 1.25,
    maxLtv: 75.0,
    dscrBands: [
      { label: 'Strong', min: 1.35, max: 99.0, ltvMax: 65.0 },
      { label: 'Adequate', min: 1.15, max: 1.3499, ltvMax: 75.0 },
      { label: 'Marginal', min: 1.0, max: 1.1499, ltvMax: 80.0 },
      { label: 'Weak', min: 0.0, max: 0.9999, ltvMax: 85.0 },
    ],
  },
  effectiveFrom: '2026-01-01T00:00:00Z',
  reviewerId: 'user_chief_underwriter',
};

export const mockConsents: ConsentRecord[] = [
  {
    id: 'consent_01',
    dealId: 'deal_metro_plaza',
    purpose: 'contact',
    scope: { channel: 'whatsapp_and_email' },
    noticeVersion: 'v2026.1',
    channel: 'whatsapp',
    recordedAt: '2026-09-01T10:32:00Z',
  },
  {
    id: 'consent_02',
    dealId: 'deal_metro_plaza',
    purpose: 'lender_submission',
    scope: { lenders: ['lender_apex_bank', 'lender_horizon_cap'] },
    noticeVersion: 'v2026.1',
    channel: 'web_upload_link',
    recordedAt: '2026-09-05T14:10:00Z',
  },
];

export const mockLenderConditions: LenderCondition[] = [
  {
    id: 'cond_01',
    dealId: 'deal_metro_plaza',
    lenderId: 'lender_apex_bank',
    originalText: 'Provide updated Phase 1 Environmental Site Assessment (ESA) report dated within 180 days of closing.',
    parsedCategory: 'documentation',
    status: 'processor_validated',
    receivedAt: '2026-09-22T09:00:00Z',
  },
  {
    id: 'cond_02',
    dealId: 'deal_metro_plaza',
    lenderId: 'lender_apex_bank',
    originalText: 'Provide copy of fully executed commercial tenant lease agreement for Suite 104 (Austin Tech Solutions).',
    parsedCategory: 'legal',
    status: 'task_created',
    receivedAt: '2026-09-22T09:00:00Z',
  },
];
